---
name: BUILD IMAGE ANSIBLE 5.5.0

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'
      - '.github/**'

jobs:  
  build:
    environment: DOCKERHUB
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the image (Ansible 5.5.0)
      - name: Build Image (Ansible 5.5.0)
        run: |
          docker build --no-cache --rm -t $GITHUB_REPOSITORY:5.5.0 -f ./ansible55.Dockerfile .
      
      # Push the image to Docker Hub (Ansible 5.5.0)
      - name: Push Version
        run: docker push $GITHUB_REPOSITORY:5.5.0